### ISSUE TITLE
Erreur PDO

### ISSUE THREAD

**Issue by sylvainmetayer** [drazik/babdelaura#152]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.datePublication_4' which is not in SELECT list; this is incompatible with DISTINCT' in /home/laura/bab-de-laura/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /home/laura/bab-de-laura/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL) #1 /home/laura/bab-de-laura/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /home/laura/bab-de-laura/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT DISTINCT...', Array, Array, NULL) #3 /home/laura/bab-de-laura/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array) #4 /home/laura/bab-de-laura/ven in /home/laura/bab-de-laura/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 195`

Présent sur les liens du menu de navigation principal, excepté "Qui suis-je ?" et "Contact"

- http://www.bricabrac-de-laura.fr/categorie/bijoux/
- http://www.bricabrac-de-laura.fr/categorie/diy/
- http://www.bricabrac-de-laura.fr/categorie/nail-art/
- http://www.bricabrac-de-laura.fr/categorie/mode-et-beaute/
- http://www.bricabrac-de-laura.fr/categorie/humeur/
- http://www.bricabrac-de-laura.fr/categorie/lifestyle/

**Comment by drazik** [comment]
Merci pour ta vigilance. Ce site n'est plus du tout maintenu et va bientôt complètement disparaître ;)
