### ISSUE TITLE
Ajouter une position sur les pages

### ISSUE THREAD

**Issue by drazik** [drazik/babdelaura#77]
Utiliser l'extension Doctrine "sortable" : 

- Ajouter `sortable: true` sous `stof_doctrine_extensions.orm.default` dans `app/config/config.yml`
- Voir comment la chose fonctionne sur https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md

**Comment by laura-v** [comment]
Pages ::
Admin ::
- [x] lister par ordre de position
- [x] ajouter flèches pour changer de position
Blog ::
- [x] Afficher par ordre de position dans le menu
- [x] Afficher par ordre de position dans le footer

Catégories ::
Admin ::
- [x] lister par ordre de position
- [x] ajouter flèches pour changer de position
Blog ::
- [x] Afficher par ordre de position dans le menu
