### ISSUE TITLE
Système de tags

### ISSUE THREAD

**Issue by laura-v** [drazik/babdelaura#82]

**Comment by laura-v** [comment]
Pour l'instant on peut ajouter, modifier, supprimer lister les tags en admin depuis les pages spéciales tags.
Il faut maintenant qu'on puisse ajouter depuis la page d'édition d'un article

**Comment by drazik** [comment]
Pour le front, utiliser ça : https://www.sitepoint.com/javascript-autocomplete-widget-awesomplete/
