### ISSUE TITLE
Supprimer un commentaire

### ISSUE THREAD

**Issue by laura-v** [drazik/babdelaura#83]

**Comment by laura-v** [comment]
Renvoie sur la page commentaires non validés

**Comment by drazik** [comment]
Il faut que ça renvoie sur la page d'où on vient

**Comment by drazik** [comment]
1. Lister les pages à partir desquelles on peut supprimer un commentaire
2. Dans les actions de ces pages, mettre l'url courante en session
3. Dans l'action de la suppression d'un commentaire, checker la session pour récupérer l'url de la page précédente, et rediriger vers celle-ci si elle existe
